-- MySQL Script generated by MySQL Workbench
-- Thu Dec 18 16:45:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema greek_business_registry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema greek_business_registry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greek_business_registry` ;
USE `greek_business_registry` ;

-- -----------------------------------------------------
-- Table `greek_business_registry`.`Doy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Doy` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Doy` (
  `doy_id` INT NULL AUTO_INCREMENT,
  `est_year` YEAR NULL,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(405) NULL,
  `insert_id` INT NOT NULL,
  PRIMARY KEY (`doy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Epimelitirio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Epimelitirio` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Epimelitirio` (
  `epimelitirio_id` INT NOT NULL AUTO_INCREMENT,
  `name_ep` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`epimelitirio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Business` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Business` (
  `business_id` INT NOT NULL AUTO_INCREMENT,
  `doy_id` INT NULL,
  `epimelitirio_id` INT NULL,
  `name` VARCHAR(45) NULL DEFAULT 'unknown',
  `regist_date` DATE NULL,
  `address` VARCHAR(100) NULL,
  `city` VARCHAR(45) NULL,
  `trade_name` VARCHAR(45) NULL,
  `postal_code` INT NULL,
  PRIMARY KEY (`business_id`),
  INDEX `fk_doy_id_idx` (`doy_id` ASC) VISIBLE,
  INDEX `fk_epim_id_idx` (`epimelitirio_id` ASC) VISIBLE,
  CONSTRAINT `fk_doy_id`
    FOREIGN KEY (`doy_id`)
    REFERENCES `greek_business_registry`.`Doy` (`doy_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_epim_id`
    FOREIGN KEY (`epimelitirio_id`)
    REFERENCES `greek_business_registry`.`Epimelitirio` (`epimelitirio_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Ipokatastima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Ipokatastima` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Ipokatastima` (
  `ipok_id` INT NOT NULL AUTO_INCREMENT,
  `businees_id` INT NULL,
  `name_ipok` VARCHAR(45) NULL,
  `perioxi` VARCHAR(45) NULL,
  PRIMARY KEY (`ipok_id`),
  CONSTRAINT `fk_business_id`
    FOREIGN KEY (`ipok_id`)
    REFERENCES `greek_business_registry`.`Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Katastatiko`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Katastatiko` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Katastatiko` (
  `katastatiko_Id` INT NOT NULL AUTO_INCREMENT,
  `business_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `type` VARCHAR(50) NULL,
  PRIMARY KEY (`katastatiko_Id`),
  CONSTRAINT `fk_business_id`
    FOREIGN KEY (`katastatiko_Id`)
    REFERENCES `greek_business_registry`.`Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Person` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Person` (
  `tax_id` CHAR(9) NOT NULL,
  `full_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  `gender` ENUM('m', 'f', 'other') NULL,
  `cv` LONGTEXT NULL,
  PRIMARY KEY (`tax_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Metoxos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Metoxos` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Metoxos` (
  `tax_id` CHAR(9) NULL,
  `pososto` DECIMAL(5,2) NULL,
  `thesi` VARCHAR(45) NULL,
  PRIMARY KEY (`tax_id`),
  CONSTRAINT `tax_id`
    FOREIGN KEY (`tax_id`)
    REFERENCES `greek_business_registry`.`Person` (`tax_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Elektis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Elektis` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Elektis` (
  `tax_id` CHAR(9) NOT NULL,
  `enarksi_thiteias` DATE NULL,
  `type` VARCHAR(45) NULL,
  `soe` TINYINT NULL,
  PRIMARY KEY (`tax_id`),
  CONSTRAINT `tax_id`
    FOREIGN KEY (`tax_id`)
    REFERENCES `greek_business_registry`.`Person` (`tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`Elegxos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`Elegxos` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`Elegxos` (
  `business_id` INT NOT NULL,
  `elegxos_id` INT NOT NULL AUTO_INCREMENT,
  `tax_id` CHAR(9) NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`elegxos_id`),
  INDEX `fk_tax_id_idx` (`tax_id` ASC) VISIBLE,
  INDEX `fk_business_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `fk_tax_id`
    FOREIGN KEY (`tax_id`)
    REFERENCES `greek_business_registry`.`Elektis` (`tax_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_business_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `greek_business_registry`.`Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greek_business_registry`.`metoxos-business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greek_business_registry`.`metoxos-business` ;

CREATE TABLE IF NOT EXISTS `greek_business_registry`.`metoxos-business` (
  `business_id` INT NOT NULL,
  `tax_id` CHAR(9) NOT NULL,
  PRIMARY KEY (`business_id`, `tax_id`),
  INDEX `fk_tax_id_idx` (`tax_id` ASC) VISIBLE,
  CONSTRAINT `fk_business_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `greek_business_registry`.`Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tax_id`
    FOREIGN KEY (`tax_id`)
    REFERENCES `greek_business_registry`.`Metoxos` (`tax_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
